[package]
name = "dupes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex-literal = "0.3.4"
sha1 = "0.10.5"
threadpool = "1.8.1"
